### ISSUE TITLE
require plist in irb leads to the following error

### ISSUE THREAD

**Issue by buk** [patsplat/plist#12]
Hi,

After _sudo gem install plist_ i am trying to get the ruby gem plist to work but typing require 'plist' in irb gives me the following error[1]

I am not sure if this is an error depending on my ruby version or a gem that is installed.

Thank you in advance for your help.

[1] https://gist.github.com/3858762

**Comment by mattbrictson** [comment]
This should be fixed in the latest plist gem (3.2.0). I'm not sure what was wrong with 3.1.7 since it not mentioned anywhere on rubygems: https://rubygems.org/gems/plist/versions
