### ISSUE TITLE
Binary plists convert nil values to <040830>

### ISSUE THREAD

**Issue by ljharb** [patsplat/plist#3]
First, when a nil value is part of a binary plist, the output contains Data <040830>. Second, apparently binary plist decoders tend not to like nil values in the list.

I'm not sure whether it would be proper to raise an exception, alter the value, display a non-binary plist in this case, or simply omit the value (or, give the gem user the choice of which).

**Comment by mattbrictson** [comment]
I'm closing since this issue is over 6 years old and I'm sure you've moved on. If you'd like to continue the discussion, let me know and I'll reopen the issue.
