### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by dabrady** [patsplat/plist#43]
The documentation links for this gem all point to RubyForge, which has been gone since 2014. Where is it hosted now?

**Comment by mattbrictson** [comment]
Good question. I am a new maintainer of this gem, and I'm still figuring this out. I think the best place to find docs is here: http://www.rubydoc.info/gems/plist

I'll update the README.

**Comment by mattbrictson** [comment]
README updated in 684ec3a

**Comment by dabrady** [comment]
🙏 Thank you!

**Comment by dabrady** [comment]
Oh, looks like there's one more place that needs to be updated: the repo description.
![image](https://user-images.githubusercontent.com/2475919/28276083-dfa86e40-6ae3-11e7-9f09-8c575a256be9.png)

**Comment by mattbrictson** [comment]
Good catch! I'm not the repo owner, so I can't change that. @patsplat?

**Comment by patsplat** [comment]
Done.  You guys make me feel old.

**Comment by patsplat** [comment]
And thanks for cleaning up the other bits @mattbrictson  @dabrady
