### ISSUE TITLE
Release plist 3.6.0

### ISSUE THREAD

**Issue by mattbrictson** [patsplat/plist#57]
I think it would be good to release a new version of the plist gem, which would include the indentation fix (#54). Any objections @patsplat ? I can take care of the release process.

**Comment by tas50** [comment]
It would be really great to get that fix up for us as well.

**Comment by patsplat** [comment]
Agreed @mattbrictson thanks

**Comment by mattbrictson** [comment]
Released 🚀

- https://rubygems.org/gems/plist/versions/3.6.0
- https://github.com/patsplat/plist/releases/tag/v3.6.0
