### ISSUE TITLE
Apostrophe entity &apos; not handled properly

### ISSUE THREAD

**Issue by one-k** [patsplat/plist#6]
The apostrophe (&apos;) gets converted into an ampersand and apos;

This test fails:

  def test_ampersand_appos
    data = Plist::parse_xml('<string>Fish&apos;s Chips</string>')
    assert_equal("Fish's Chips", data)
  end

I'm having trouble seeing where these entities are processed. If someone could point me in the right direction, I'd be happy to help.

J

**Comment by mattbrictson** [comment]
This seems to work fine as of Ruby 2.1 (which as of this writing is the oldest supported version of Ruby).

```
irb(main):001:0> plist = { "key" => "Val'ue" }.to_plist
=> "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n<plist version=\"1.0\">\n<dict>\n\t<key>key</key>\n\t<string>Val&#39;ue</string>\n</dict>\n</plist>\n"
irb(main):002:0> Plist.parse_xml _
=> {"key"=>"Val'ue"}
```
